### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by artemklevtsov** [dselivanov/RestRserve#33]
We should add some tests about:

Classes (constructor and methods):
- [x] `RestRserveRequest` (added in 323db685ed146587b1c019522ee333660314de56)
- [x] `RestRserveResponse` (added in 323db685ed146587b1c019522ee333660314de56)
- [x] `HTTPErrorFactory` (added in 323db685ed146587b1c019522ee333660314de56)
- [ ] `RestRserveApplication`
- [x] `RestRserveMiddleware` (added in 323db685ed146587b1c019522ee333660314de56)
- [x] `RestRserveRouter` (added in 10d619a230ffa75772a179440629ebc532d85378)

Functions: 
- [x] `raise` (added in 323db685ed146587b1c019522ee333660314de56)
- [x] `try_capture_stack` (added in #43)
- [x] `deparse_vector` (added in #43)
- [x] `get_traceback` (added in #43)
- [x] `URLenc` (added in #43)
- [x] `dict_` functions (removed in #43)
- [x] `parse_query` (added in d3ac6efc1a85bdb33b17fc26258d6b86acba6fdd)
- [x] `parse_headers` (added in d3ac6efc1a85bdb33b17fc26258d6b86acba6fdd)
- [x] `extract_docstrings_yaml` (added in ab19b6a0f6f84a27209f5dab4230f7062d944572)
- [x] `guess_mime` (added in #43)
- [x] `is_string` (added in #43)
- [x] `is_path` (added in #43)

Running server:
- [x] Static files (added in 1763f86de1e31e3a107d62444dcf5bcfd0532623)
- [x] Static directories (added in 1763f86de1e31e3a107d62444dcf5bcfd0532623)
- [x] Middleware (added in 1763f86de1e31e3a107d62444dcf5bcfd0532623)
- [x] OpenAPI (added in b81cfc08c04c91f50d5931053db2fb13d2be3083)
- [x] Swagger UI (added in b81cfc08c04c91f50d5931053db2fb13d2be3083)
- [x] Basic Auth (added in 1763f86de1e31e3a107d62444dcf5bcfd0532623)
- [x] OAuth (added in 1763f86de1e31e3a107d62444dcf5bcfd0532623)

**Comment by artemklevtsov** [comment]
Tasks status updated.
